spring:
  datasource:
    url: jdbc:postgresql://awseb-e-ezjnxfjb44-stack-awsbrdsdatabase-f2ocmocry5g.celwdmxhcr1.na-east-1.rds.amazonaws.com:5432/customer
    username: root
    password: password

aws:
  s3:
    mock: false