server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/customer
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true

cors:
  allowed-origins: http://localhost:5173, http://localhost:3000
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"