name: CI - Build Backend

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
    paths:
      - backend/**

jobs:
  builds:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.5
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: customer
        ports:
          - "5433:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Setup Java & Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build and run Unit & Integration tests with Maven
        run: mvn -ntp -B verify
