name: CI - Build & Test React Frontend

on:
  pull_request:
    branches:
      - "main"
    paths:
      - frontend/react/**

jobs:
  builds:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/react
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Node 18 & Caching global packages data
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/react/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Test code with coverage
        continue-on-error: true
        id: run-tests
        run: npm run coverage

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: frontend/react/coverage